import ast
import csv
import math
import os
import pathlib
import pickle
import pprint
import shutil
import re
import sys
import time
import nltk

import transformers.general
import transformers.basic
from util.JoinEval import JoinEval
from util.dataset import sample_data

from classifier.classifierutil import get_gold_label, get_gpt_label
from classifier import classifierutil

from transformers.numeric import get_numeric_function
from transformers.algorithmic import get_algorithmic_function
from transformers.general import get_bridge_values
from transformers.string import get_string_function

transformers.general.USE_TQDM = True
transformers.basic.USE_TQDM = True

import preprocessors
from llm_logging import configure_llm_logging, flush_llm_summary, set_llm_context

BASE_PATH = pathlib.Path(__file__).absolute().parent.parent.parent.absolute()
ED_CACHE_PATH = BASE_PATH / "cache/edit_distance/ed.pkl"

# Deepseek only supports general and basic types.
# MODEL_NAME = "gpt-4o-2024-05-13"  # ["gpt-4o-2024-05-13", "gpt-4o-mini-2024-07-18", "llama3.1-8b", "deepseek-chat"]
# PROMPT_VERSION = "v001"
# BASIC_PROMPT = False  # Ignore framework and directly prompt the LLM


# EXAMPLE_SIZE = 5
# EXAMPLE_SIZE_TYPE = "fixed"
# MATCHING_TYPE = 'edit_dist'  # ["exact", "edit_dist"]
# CLASSIFICATION_TYPE = 'golden'  # ['golden', gpt_classifier', 'all_string']

MODEL_NAME = "gpt-4o-mini-2024-07-18"
PROMPT_VERSION = "v001"
BASIC_PROMPT = False

# Example-selection configuration.
#
# Fixed mode:
#   TABULAX_EXAMPLE_SIZE_TYPE=fixed
#   TABULAX_EXAMPLE_SIZE=5
#
# Fraction mode:
#   TABULAX_EXAMPLE_SIZE_TYPE=fraction
#   TABULAX_EXAMPLE_FRACTION=0.25

_example_size_text = os.getenv(
    "TABULAX_EXAMPLE_SIZE",
    "10",
).strip()

# Allow TABULAX_EXAMPLE_SIZE to be empty in fraction mode.
EXAMPLE_SIZE = int(_example_size_text) if _example_size_text else 10

EXAMPLE_SIZE_TYPE = os.getenv(
    "TABULAX_EXAMPLE_SIZE_TYPE",
    "fixed",
).strip().lower()

EXAMPLE_FRACTION = float(
    os.getenv(
        "TABULAX_EXAMPLE_FRACTION",
        "0.25",
    )
)

if EXAMPLE_SIZE_TYPE not in {
    "fixed",
    "fraction",
    "percentage",
    "percent",
}:
    raise ValueError(
        "TABULAX_EXAMPLE_SIZE_TYPE must be 'fixed' or 'fraction', "
        f"got {EXAMPLE_SIZE_TYPE!r}"
    )

if EXAMPLE_SIZE_TYPE != "fixed" and not 0 < EXAMPLE_FRACTION < 1:
    raise ValueError(
        "TABULAX_EXAMPLE_FRACTION must be greater than 0 and "
        f"less than 1, got {EXAMPLE_FRACTION}"
    )
# - TABULAX_MATCHING_TYPE=edit_dist for single matching type
# - TABULAX_MATCHING_TYPES=edit_dist,exact lets us evaluate both from one LLM run
MATCHING_TYPE = os.getenv("TABULAX_MATCHING_TYPE", "edit_dist")
MATCHING_TYPES = [
    x.strip()
    for x in os.getenv("TABULAX_MATCHING_TYPES", MATCHING_TYPE).split(",")
    if x.strip()
]

CLASSIFICATION_TYPE = "gpt_classifier"

TEST_ON_ALL_DATA = False

DS_PATH = os.getenv("TABULAX_DS_PATH", str(BASE_PATH / "data/autofj/Amphibian"))
DS_NAME = os.getenv("TABULAX_DS_NAME", pathlib.Path(DS_PATH).name)


class_str = "" if CLASSIFICATION_TYPE == "golden" else f"_{CLASSIFICATION_TYPE}"
if BASIC_PROMPT:
    class_str = "_BASIC-PROMPT"


model_str = MODEL_NAME.replace("-2024-05-13", "").replace("-2024-07-18", "")
OUTPUT_DIR = pathlib.Path(os.getenv("TABULAX_OUTPUT_DIR", str(BASE_PATH / "outputs" / DS_NAME)))

# Init edit distance cache
ed_cache_dict = None
is_ed_updated = [False]

if os.path.exists(ED_CACHE_PATH):
    with open(ED_CACHE_PATH, 'rb') as fp:
        ed_cache_dict = pickle.load(fp)
else:
    ed_cache_dict = {}



def _save_ed_cache():
    if not is_ed_updated[0]:
        return
    with open(ED_CACHE_PATH, 'wb') as fp:
        pickle.dump(ed_cache_dict, fp)
    is_ed_updated[0] = False


def edit_distance_func(val1, val2):
    tup = (val1, val2)
    if tup not in ed_cache_dict:
        ed_cache_dict[tup] = nltk.edit_distance(val1, val2)
        is_ed_updated[0] = True
    return ed_cache_dict[tup]



def get_classes(method, tbl_name, ds_path, train_examples=None):
    if method == "golden":
        return get_gold_label(tbl_name, ds_path)
    elif method == "gpt_classifier":
        return get_gpt_label(
            tbl_name,
            ds_path,
            train_examples=train_examples,
            model_name=MODEL_NAME,
            prompt_version=PROMPT_VERSION,
        )
    elif method == "all_string":
        return "String"
    else:
        raise NotImplementedError(f"Classification Method {method} not implemented")



def get_function_from_string(function_string):
    # """Generated By ChatGPT"""
    # Parse the function string into an abstract syntax tree (AST)

    try:
        parsed_ast = ast.parse(function_string)
    except SyntaxError:
        import sys
        print("Could not parse function string", file=sys.stderr)
        parsed_ast = ast.parse("def error_res(s): return s")

    # Extract the function definition node
    function_def_node = next((node for node in ast.walk(parsed_ast) if isinstance(node, ast.FunctionDef)), None)

    if function_def_node:
        # Compile the AST into a code object
        code_object = compile(parsed_ast, filename='<string>', mode='exec')

        # Execute the code object in a specific namespace
        namespace = {}
        exec(code_object, namespace)

        # Return the function from the namespace
        return namespace.get(function_def_node.name)

    return None


def extract_functions_lines_with_body(input_string):
    """
    Extract full Python function definitions from an LLM response.

    The old regex stopped at blank lines inside the function body, which caused
    GPT-5-mini functions to be truncated and return None.
    """
    if input_string is None:
        return []

    # Remove markdown fences if the model returns them.
    cleaned = input_string.strip()
    cleaned = re.sub(r"^```(?:python)?\s*", "", cleaned)
    cleaned = re.sub(r"\s*```$", "", cleaned)

    try:
        tree = ast.parse(cleaned)
    except SyntaxError:
        # Fallback: keep old behavior for malformed responses.
        pattern = re.compile(
            r'(def\s+[a-zA-Z_][a-zA-Z0-9_]*\s*\([^)]*\):[^\n]*((?:\n[ \t]+.*|\n\s*)*)*)'
        )
        matches = pattern.findall(cleaned)
        return [match[0] for match in matches]

    funcs = []
    lines = cleaned.splitlines()

    for node in tree.body:
        if isinstance(node, ast.FunctionDef):
            start = node.lineno - 1
            end = getattr(node, "end_lineno", None)
            if end is not None:
                funcs.append("\n".join(lines[start:end]))

    return funcs



def get_transformations(funcs_list):

    funcs_str = extract_functions_lines_with_body(funcs_list)
    return [get_function_from_string(f) for f in funcs_str], funcs_str


def normalize_generated_value(val):
    """
    Normalize LLM-generated transformation output before postprocessing.

    GPT-5-mini sometimes returns strings like:
      Expected Output:"Some Target"
    instead of only:
      Some Target
    """
    if val is None:
        return ""

    if type(val) is not str:
        val = str(val)

    val = val.strip()

    # Remove common prompt-format wrappers.
    m = re.match(r'^Expected Output:\s*["\']?(.*?)["\']?\s*$', val, flags=re.IGNORECASE | re.DOTALL)
    if m:
        val = m.group(1).strip()

    m = re.match(r'^Output:\s*["\']?(.*?)["\']?\s*$', val, flags=re.IGNORECASE | re.DOTALL)
    if m:
        val = m.group(1).strip()

    # Remove one layer of matching quotes.
    if len(val) >= 2 and val[0] == val[-1] and val[0] in ("'", '"'):
        val = val[1:-1].strip()

    return val


def parse_numeric_value(val):
    """
    Convert numeric join values to float safely.

    The numeric transformer can return strings such as "37.0" while the
    numeric join path expects numbers. This helper keeps those string outputs
    valid and lets unparseable values count as no prediction instead of
    crashing the run.
    """
    if val is None:
        raise ValueError("Cannot parse None as a number")

    if isinstance(val, (int, float)):
        if isinstance(val, float) and math.isnan(val):
            raise ValueError("Cannot parse NaN as a number")
        return float(val)

    text = str(val).strip()
    if not text:
        raise ValueError("Cannot parse empty string as a number")

    # Handle common formatting in numeric datasets.
    text = text.replace(",", "")
    text = text.replace("−", "-")  # unicode minus
    text = text.replace("°", "")

    return float(text)


def join(rows, transformation, matching_type):
    # return [("", "")], [{'inp': "inp", 'gen': "res", 'exp': "out"}]

    sources = []
    targets = []

    for row in rows:
        inp, out = row[0], row[1]
        sources.append(inp)
        targets.append(out)


    joins = []
    predicts = []

    for row in rows:
        inp, out = row[0], row[1]
        try:
            val = transformation(inp)
        except Exception as e:
            val = None
        val = normalize_generated_value(val)

        raw_val = "" if val is None else val
        if type(raw_val) is not str:
            raw_val = str(raw_val)

        if matching_type == 'edit_dist':
            min_dist = 100000
            min_key = None
            for target in targets:
                dist = edit_distance_func(target, val)
                if dist < min_dist:
                    min_dist = dist
                    min_key = target

            res, pred = min_key, val

        elif matching_type == 'exact':
            res = val if val in targets else None
            pred = val

        elif matching_type == "num_dist":
            min_dist = float("inf")
            min_key = None
            pred = raw_val

            try:
                val_num = parse_numeric_value(val)
            except (TypeError, ValueError, OverflowError):
                val_num = None

            if val_num is not None:
                for target in targets:
                    try:
                        target_num = parse_numeric_value(target)
                    except (TypeError, ValueError, OverflowError):
                        continue

                    dist = abs(target_num - val_num)
                    if dist < min_dist:
                        min_dist = dist
                        min_key = target

            res = str(min_key) if min_key is not None else None

        else:
            raise Exception("Wrong matching type.")


        if pred is None:
            pred = ""
        predicts.append({'inp': inp, 'gen': res, 'exp': out, 'pred': pred})
        if res is not None:
            joins.append((str(inp), str(res)))


    return joins, predicts

def preprocess(table, pipline):
    test = [(src, tar, src) for src, tar in table['test']]
    train = [(src, tar, src) for src, tar in table['train']]

    details = []

    for process in pipline:
        func = getattr(preprocessors, process)
        train, test, detail = func(train, test, {
            'model_name': MODEL_NAME,
            'prompt_version': PROMPT_VERSION,
        })
        details.append(detail)


    return {
        'train': train,
        'test': test
    }, details


# ---------------------------------------------------------------------------
# Standardized prediction output (output-boundary only).
#
# Shared schema (see AutomaticFuzzyJoin/scripts/run_vida_autofj.py and
# lotus/scripts/run_sem_sim_join.py FAMILY_LAYOUTS):
#
#   target_id,target_value,source_id,source_value,score,score_type
#
# Canonical VIDA raw orientation per family:
#   autofj / autofj_overlap: target table = left.csv, source table = right.csv
#   kbwt / ss / wt:          target table = target.csv, source table = source.csv
#
# TabulaX internally transforms the ground-truth first column (its input side)
# into the ground-truth second column (its output side). For kbwt/ss/wt those
# raw sides are source.csv / target.csv, already aligned with the canonical
# orientation. For autofj/autofj_overlap the raw input side is left.csv (the
# canonical target) and the output side is right.csv (the canonical source),
# so this adapter swaps the roles at the output boundary only.
#
# For each matched prediction row:
#   * gen is the target-side value TabulaX actually selected (edit_dist, exact,
#     num_dist). exp is ground truth and is never used here.
#   * the raw input-side value is the third element of the corresponding
#     processed test row, which preserves the original raw string for every
#     class (String/Algorithmic, General bridge, Numbers).
#
# IDs come from exact raw-string matching against the raw tables only. GT is
# never consulted. Duplicate raw join values yield a blank ID.
# ---------------------------------------------------------------------------

STANDARDIZED_PREDICTION_HEADER = [
    "target_id",
    "target_value",
    "source_id",
    "source_value",
    "score",
    "score_type",
]

STANDARDIZED_FAMILIES = frozenset(
    {"autofj", "autofj_overlap", "kbwt", "ss", "wt"}
)

# Canonical raw files per family: (target table filename, source table filename).
_FAMILY_RAW_FILES = {
    "autofj": ("left.csv", "right.csv"),
    "autofj_overlap": ("left.csv", "right.csv"),
    "kbwt": ("target.csv", "source.csv"),
    "ss": ("target.csv", "source.csv"),
    "wt": ("target.csv", "source.csv"),
}


def _strip_header_names(headers):
    return [str(header).strip() for header in headers]


def _find_column(headers, name):
    """Case-insensitive lookup of a raw CSV column name (returns the stripped
    header as stored, or None)."""
    if name is None:
        return None
    folded = {header.casefold(): header for header in _strip_header_names(headers)}
    return folded.get(str(name).strip().casefold())


def _read_rows_txt_columns(table_dir):
    """Read the canonical ``<source_col>:<target_col>`` mapping from rows.txt.

    The tokens are the column names of the TabulaX input (source) side and the
    output (target) side; they match the corresponding raw table headers.
    """
    rows_path = table_dir / "rows.txt"
    try:
        lines = rows_path.read_text(encoding="utf-8", errors="replace").splitlines()
    except OSError:
        return None, None
    for line in lines:
        line = line.strip()
        if line and ":" in line:
            src_col, tgt_col = line.split(":", 1)
            return src_col.strip(), tgt_col.strip()
    return None, None


def _load_raw_join_table(table_dir, filename, rows_txt_column):
    """Return ``(join_column, [(row_id, raw_value), ...])`` or ``(None, None)``.

    Values are preserved exactly as stored (no stripping, no type coercion),
    using a plain CSV reader with ``utf-8-sig`` so BOMs, quoted commas and
    leading-zero text survive. ``row_id`` is the stored ``id`` cell when the
    file has an ``id`` column (AutoFJ family) and the zero-based row index
    otherwise (kbwt/ss/wt).
    """
    path = table_dir / filename
    try:
        with open(path, "r", encoding="utf-8-sig", newline="") as handle:
            reader = csv.reader(handle)
            headers = [str(header).strip() for header in next(reader)]
            join_col = _find_column(headers, rows_txt_column)
            if join_col is None and len(headers) == 1:
                join_col = headers[0]
            if join_col is None:
                return None, None
            id_col = _find_column(headers, "id")
            join_index = headers.index(join_col)
            id_index = headers.index(id_col) if id_col is not None else None
            rows = []
            for row_index, record in enumerate(reader):
                value = record[join_index] if len(record) > join_index else ""
                if id_index is not None:
                    row_id = record[id_index] if len(record) > id_index else ""
                else:
                    row_id = str(row_index)
                rows.append((row_id, value))
            return join_col, rows
    except Exception:
        return None, None


def _resolve_table_dir_and_family(table, ds_path):
    """Return ``(table_dir, family)`` or ``(None, None)``.

    Handles both the current single-table ``DS_PATH`` (``<root>/<family>/<table>``
    containing rows.txt directly) and the multi-table loading structure (``DS_PATH``
    = family root, each ``table`` a sub-directory holding rows.txt).
    """
    ds_path = pathlib.Path(ds_path)
    if (ds_path / "rows.txt").is_file():
        table_dir = ds_path
    else:
        table_dir = ds_path / table
    if not (table_dir / "rows.txt").is_file():
        return None, None
    family = table_dir.parent.name
    if family not in STANDARDIZED_FAMILIES:
        return None, None
    return table_dir, family


def _resolve_standardized_context(table, ds_path):
    """Resolve the raw lookup data for one table, or None if unavailable."""
    table_dir, family = _resolve_table_dir_and_family(table, ds_path)
    if table_dir is None:
        return None

    target_filename, source_filename = _FAMILY_RAW_FILES[family]
    input_col, output_col = _read_rows_txt_columns(table_dir)

    # rows.txt is ordered (TabulaX input-side column, output-side column).
    # Map each canonical side to the raw file that stores it.
    if family in ("autofj", "autofj_overlap"):
        # canonical target = left.csv = TabulaX input side.
        target_join_col, target_rows = _load_raw_join_table(
            table_dir, target_filename, input_col
        )
        source_join_col, source_rows = _load_raw_join_table(
            table_dir, source_filename, output_col
        )
    else:
        # canonical source = source.csv = TabulaX input side.
        source_join_col, source_rows = _load_raw_join_table(
            table_dir, source_filename, input_col
        )
        target_join_col, target_rows = _load_raw_join_table(
            table_dir, target_filename, output_col
        )

    if target_join_col is None or source_join_col is None:
        return None

    return {
        "family": family,
        "table_dir": table_dir,
        "target_rows": target_rows,
        "source_rows": source_rows,
    }


def _lookup_row_id_and_value(rows, key):
    """Map a raw join value to (id, canonical value).

    Exactly one raw row match -> its stored id/index and raw cell.
    Zero or multiple matches -> blank id; the caller's value is kept.
    Never picks a duplicate row arbitrarily and never uses ground truth.
    """
    if key is None:
        key = ""
    key = str(key)
    matches = [row for row in rows if row[1] == key]
    if len(matches) == 1:
        return matches[0][0], matches[0][1]
    return "", key


def write_standardized_predictions(
    table,
    eval_matching_type,
    test_rows,
    predicts,
    ds_path,
    output_dir,
):
    """Write ``<table>_<eval_matching_type>_predictions.csv`` (additive).

    Emits one row per matched prediction (``gen`` is not None); ``gen`` is the
    target-side value selected by TabulaX for edit_dist/exact/num_dist. Rows
    with no match (``gen=None``) are not emitted, and wrong matches with a
    non-null ``gen`` are kept. ``score`` and ``score_type`` are blank.

    Returns the number of prediction rows written (0 if skipped).
    """
    context = _resolve_standardized_context(table, ds_path)
    if context is None:
        table_dir, family = _resolve_table_dir_and_family(table, ds_path)
        if family is not None:
            print(
                f"[TabulaX standardized] could not resolve the raw join context "
                f"for {family}/{table}; skipping "
                f"{table}_{eval_matching_type}_predictions.csv",
                file=sys.stderr,
            )
        return 0

    family = context["family"]
    rows = []
    for predict, test_row in zip(predicts, test_rows):
        gen = predict.get("gen")
        if gen is None:
            continue

        raw_input = test_row[2] if len(test_row) >= 3 else predict.get("inp")
        if raw_input is None:
            raw_input = ""
        gen = str(gen)

        if family in ("autofj", "autofj_overlap"):
            # target = left.csv (TabulaX input side); source = right.csv (gen side).
            target_id, target_value = _lookup_row_id_and_value(
                context["target_rows"], raw_input
            )
            source_id, source_value = _lookup_row_id_and_value(
                context["source_rows"], gen
            )
        else:
            # source = source.csv (TabulaX input side); target = target.csv (gen side).
            source_id, source_value = _lookup_row_id_and_value(
                context["source_rows"], raw_input
            )
            target_id, target_value = _lookup_row_id_and_value(
                context["target_rows"], gen
            )

        rows.append(
            [target_id, target_value, source_id, source_value, "", ""]
        )

    output_path = pathlib.Path(output_dir) / (
        f"{table}_{eval_matching_type}_predictions.csv"
    )
    try:
        with open(output_path, "w", encoding="utf-8", newline="") as handle:
            writer = csv.writer(handle)
            writer.writerow(STANDARDIZED_PREDICTION_HEADER)
            writer.writerows(rows)
    except Exception as exc:
        print(
            f"[TabulaX standardized] could not write {output_path.name}: {exc!r}",
            file=sys.stderr,
        )
        return 0

    print(
        f"[TabulaX standardized] wrote {len(rows)} prediction row(s) to "
        f"{output_path.name}"
    )
    return len(rows)



def main():
    if os.path.exists(OUTPUT_DIR):
        shutil.rmtree(OUTPUT_DIR)
    pathlib.Path(OUTPUT_DIR).mkdir(parents=True, exist_ok=True)

    if EXAMPLE_SIZE_TYPE == "fixed":
        print(
            f"[TabulaX config] example sampling: "
            f"fixed count={EXAMPLE_SIZE}"
        )
    else:
        print(
            f"[TabulaX config] example sampling: "
            f"ceil({EXAMPLE_FRACTION} * gt_size), minimum 1"
        )

    print(
        f"[TabulaX config] example seed: "
        f"{os.getenv('TABULAX_EXAMPLE_SEED', '12345')}"
    )

    configure_llm_logging(
        OUTPUT_DIR,
        dataset=pathlib.Path(DS_PATH).name,
        ds_name=DS_NAME,
        ds_path=DS_PATH,
        model_name=MODEL_NAME,
        prompt_version=PROMPT_VERSION,
        basic_prompt=BASIC_PROMPT,
        example_size=EXAMPLE_SIZE,
        example_size_type=EXAMPLE_SIZE_TYPE,
        matching_type=",".join(MATCHING_TYPES),
        classification_type=CLASSIFICATION_TYPE,
    )

    out_file_path = OUTPUT_DIR / "_res.csv"

    tables = sample_data(DS_PATH, EXAMPLE_SIZE, EXAMPLE_SIZE_TYPE)


    f = open(out_file_path, 'w', encoding='utf-8', newline='')

    title_str = "id,matching_type,class,P,R,F1,correct,len,gen_functions,avg_edit_dist,avg_norm_edit_dist,Time"
    print(title_str)
    i = 1
    if f is not None:
        print(title_str, file=f)

    for table in tables:
        start_time = time.time()

        print(f"{i}/{len(tables)}: {table}", end=',')
        set_llm_context(table=table, table_index=i)
        i += 1

        cls = get_classes(
            CLASSIFICATION_TYPE,
            table,
            DS_PATH,
            train_examples=tables[table]['train'],
        )
        assert cls in classifierutil.ALLOWED_CLASSES

        if BASIC_PROMPT:
            pre_pipeline = ["get_basic_bridge"]
        elif cls == "Numbers":
            pre_pipeline = ["parse_numbers"]
        elif cls == "General":
            pre_pipeline = ["get_bridge_table"]
        else:
            pre_pipeline = []
        new_table, preprocess_details = preprocess(tables[table], pre_pipeline)
        tables[table] = new_table

        # (bridge, target, src)

        train = tables[table]['train']
        test = tables[table]['test']
        if TEST_ON_ALL_DATA:
            test = test + tables[table]['train']

        matching_type = MATCHING_TYPE

        if cls == "General" or BASIC_PROMPT:
            #  Most of the work is done in preprocessing
            details, funcs_list = {}, "def transform_source_to_target1(value): return value"
        elif cls == "Numbers":
            details, funcs_list = {}, get_numeric_function(train)
            matching_type = "num_dist"
        elif cls == "Algorithmic":
            details, funcs_list = get_algorithmic_function(train, model_name=MODEL_NAME, prompt_version=PROMPT_VERSION)
            # matching_type = "exact"
        elif cls == "String":
            details, funcs_list = get_string_function(train, model_name=MODEL_NAME, prompt_version=PROMPT_VERSION)
        else:
            raise NotImplementedError()



        funcs, funcs_str = get_transformations(funcs_list)

        details['funcs_str'] = funcs_str

        if matching_type == "num_dist":
            eval_matching_types = ["num_dist"]
        else:
            eval_matching_types = MATCHING_TYPES

        for eval_matching_type in eval_matching_types:
            eval_start_time = time.time()

            if len(funcs) > 0:
                joins, predicts = join(test, funcs[0], eval_matching_type)
            else:
                joins, predicts = [], []

            # Standardized prediction CSV (additive output-boundary writer).
            write_standardized_predictions(
                table,
                eval_matching_type,
                test,
                predicts,
                DS_PATH,
                OUTPUT_DIR,
            )

            avg_edit_dist = sum(
                edit_distance_func(p['pred'], p['exp']) for p in predicts
            ) / len(predicts) if len(predicts) != 0 else math.nan

            avg_norm_edit_dist = sum(
                edit_distance_func(p['pred'], p['exp']) / max(len(p['pred']), len(p['exp'])) for p in predicts
            ) / len(predicts) if len(predicts) != 0 else 1

            correct_cnt = sum(1 if p['pred'] == p['exp'] else 0 for p in predicts)

            test_strs = [(str(t[0]), t[1], t[2]) for t in test]
            je = JoinEval(joins, test_strs)

            taken_time = time.time() - start_time
            eval_time = time.time() - eval_start_time

            val_str = f"{eval_matching_type},{cls},{je.short_str()},{correct_cnt},{len(predicts)},{len(details['funcs_str'])},{avg_edit_dist},{avg_norm_edit_dist},{taken_time}"
            print(val_str)

            if f is not None:
                print(f"{table},{val_str}", file=f)

            with open(OUTPUT_DIR / f"{table}_{eval_matching_type}.txt", 'w', encoding='utf-8', errors='replace') as f2:
                print(f"P, R, F = {je.short_str()}", file=f2)
                print(f"Class: {cls}", file=f2)
                print(f"Matching Type: {eval_matching_type}", file=f2)
                print(f"Correct Predictions: {correct_cnt}", file=f2)
                print(f"Input Count: {len(predicts)}", file=f2)
                print(f"Average Edit Distance: {avg_edit_dist}", file=f2)
                print(f"Average Normalized Edit Distance: {avg_norm_edit_dist}", file=f2)
                print(f"Taken Time: {taken_time}", file=f2)
                print(f"Eval/Postprocess Time: {eval_time}", file=f2)
                print(f"Generated Functions: {len(details['funcs_str'])}", file=f2)
                print(f"Details: {details}", file=f2)
                # print(f"Prompt: {details['prompt']}", file=f2)
                print(f"Preprocessing details: {pprint.pformat(preprocess_details, indent=1, width=120)}", file=f2)
                print("\n\n===========\n\n", file=f2)
                print(f"Table (processed src, target, src): {pprint.pformat(tables[table], indent=1, width=120)}", file=f2)

                print("\n\n===========\n\nPredictions:\n", file=f2)

                for pred in predicts:
                    print(pred, file=f2)

            _save_ed_cache()

    f.close()
    flush_llm_summary(completed=True)


if __name__ == "__main__":
    main()
